### ISSUE TITLE
Roadmap (WIP)

### ISSUE THREAD

**Issue by mfrachet** [progressively-crew/progressively#768]
_In progress_

## Transerve

- [x] Add batch processing with Kafka

## Feature flags

Tbd

## Quantitative analytics

- [x] Find a way to effectively store the events => clickhouse
- [x] Find a way to effectively compute the analytics insights => clickhouse
- [ ] Experiment with materialised views / tables to optimize query in clickhouse

## Funnels

- [] Compute funnels through clickhouse (try using materialised views) and eventually sampling

## Qualitative analytics

- []~~Check how to integrate [heatmapjs](https://www.patrick-wied.at/static/heatmapjs/) or something similar~~
- [] Use a grid clustering algorithm to create a grid on the page and show the most active areas
- [] Experiment with materialised views / tables to optimize query in clickhouse

## Error & exceptions

Tbd

## Session Recording

Tbd
